version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  s3ninja:
    image: scireum/s3-ninja:latest
    environment:
      S3_ACCESS_KEY_ID: "accessKey"
      S3_SECRET_ACCESS_KEY: "secretKey"
      S3_REGION: "us-east-1"
    ports:
      - "9000:9000"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
